spring:
  application:
    name: pdf-processor-ui
  
  # Database configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/pdf_processor
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    
  # JPA configuration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false
    
  # File upload configuration
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

# Server configuration
server:
  port: 8080
  servlet:
    context-path: /

# Analysis service configuration
analysis:
  python:
    service:
      url: ${PYTHON_SERVICE_URL:http://localhost:8000}
  results:
    dir: ${ANALYSIS_RESULTS_DIR:./analysis_results}
  timeout: ${ANALYSIS_TIMEOUT:300000}

# File upload directory
file:
  upload:
    dir: ${FILE_UPLOAD_DIR:./uploads}

# Logging configuration
logging:
  level:
    com.pdfprocessor: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Vaadin configuration
vaadin:
  productionMode: false
  closeIdleSessions: true
  heartbeatInterval: 300